### ISSUE TITLE
Windows sln generation issue.

### ISSUE THREAD

**Issue by sujay46** [alicevision/AliceVision#355] opened 2018-02-10 07:33 UTC
Hi, I am not able to generate the .sln file. This is my log. I tried changing Visual studio versions. Also made sure that I am not building cmake on src/cmakelists.txt file. 

The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_arm/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_arm/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_arm/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_arm/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
** ALICEVISION_BUILD_DOC: 'AUTO'
** ALICEVISION_USE_OPENMP: 'AUTO'
** ALICEVISION_USE_CCTAG: 'AUTO'
** ALICEVISION_USE_POPSIFT: 'AUTO'
** ALICEVISION_USE_OPENGV: 'AUTO'
** ALICEVISION_USE_ALEMBIC: 'AUTO'
** ALICEVISION_USE_OPENCV: 'OFF'
target changed from "" to "auto"
Detected: Vendor ID 'GenuineIntel'   CPU Family '6'  CPU Model '94'  CPU Flags  ''
CMake Warning at src/cmakeFindModules/OptimizeForArchitecture.cmake:88 (message):
  Your CPU (family 6, model 94) is not known.  Auto-detection of optimization
  flags failed and will use the 65nm Core 2 CPU settings.
Call Stack (most recent call first):
  src/cmakeFindModules/OptimizeForArchitecture.cmake:150 (AutodetectHostArchitecture)
  src/CMakeLists.txt:29 (OptimizeForArchitecture)

Detected CPU: merom
Performing Test check_c_compiler_flag__arch_SSE2
Performing Test check_c_compiler_flag__arch_SSE2 - Failed
Performing Test check_cxx_compiler_flag__arch_SSE2
Performing Test check_cxx_compiler_flag__arch_SSE2 - Failed
Checking for C++11 compiler
Checking for C++11 compiler - available
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
OpenMP found.
-- Did not find MOSEK header
-- Did not find MOSEK library
Could not find mosek library on this machine.
Eigen 3.2.4 found (include: E:/AliceVision/AliceVision/src/dependencies/eigen)
Trying to find package Ceres for aliceVision: 
No external CERES detected, using the embedded one.
Flann 1.8.4 found (include: E:/AliceVision/AliceVision/src/dependencies/flann/src/cpp/flann)
CoinUtils 2.9.3 found (include: E:/AliceVision/AliceVision/src/dependencies/osi_clp/CoinUtils/src)
Clp 1.15.11 found (include: E:/AliceVision/AliceVision/src/dependencies/osi_clp/Clp/src)
Osi 0.106.10 found (include: E:/AliceVision/AliceVision/src/dependencies/osi_clp/Osi/src/Osi)
Lemon  found (include: E:/AliceVision/AliceVision/src/dependencies/lemon/lemon)
CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Warning at C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:873 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindBoost.cmake:1501 (_Boost_MISSING_DEPENDENCIES)
  src/CMakeLists.txt:311 (find_package)

CMake Error at src/CMakeLists.txt:316 (message):
  Failed to find Boost.

Looking for Alembic. 1.5.8
trying to found the all-in-one libAlembic.so
all-in-one not found, try finding individual ones --  ABC_LIBRARY_ALLINONE-NOTFOUND
ABC_LIBRARIES: ABC_LIBRARY-NOTFOUND;ABC_GEOM-NOTFOUND;ABC_COREHDF5-NOTFOUND;ABC_COREABSTRACT-NOTFOUND;ABC_UTIL-NOTFOUND;ABC_COREFACTORY-NOTFOUND;ABC_OGAWA-NOTFOUND;ABC_COREOGAWA-NOTFOUND;ABC_COLLECTION-NOTFOUND;C:/ProgramData/Anaconda2/Library/lib/hdf5.lib;C:/ProgramData/Anaconda2/Library/lib/hdf5_hl.lib;-ldl;ABC_OPENEXR_LIBS-NOTFOUND;ABC_ILMBASE_IEX-NOTFOUND;ABC_ILMBASE_HALF-NOTFOUND
ABC_INCLUDE_DIR: ABC_INCLUDE_DIR-NOTFOUND;ABC_HALF_INCLUDE_DIR-NOTFOUND
Could NOT find Alembic (missing: ABC_LIBRARIES ABC_LIBRARY_DIR ABC_INCLUDE_DIR) 
Alembic NOT FOUND
Found PythonInterp: C:/ProgramData/Anaconda2/python.exe (found version "2.7.13") 
Could NOT find Wget (missing: WGET_EXECUTABLE) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE) 
Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of long long
Check size of long long - done
Found Threads: TRUE  
Eigen 3.2.4 found (include: E:/AliceVision/AliceVision/src/dependencies/eigen)
-- Found Eigen version 3.2.4: E:/AliceVision/AliceVision/src/dependencies/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

A library with BLAS API not found. Please specify library location.
LAPACK requires BLAS
-- Did not find LAPACK library, disabling LAPACK support.
-- Did not find BLAS library, disabling LAPACK support.
-- Building without SuiteSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building with OpenMP.
Looking for C++ include unordered_map
Looking for C++ include unordered_map - found
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
Looking for C++ include memory
Looking for C++ include memory - found
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
-- Do not build any example.
CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:18 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/dependencies/flann/CMakeLists.txt:22 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

Configured Eigen 3.2.4

Could NOT find PopSift (missing: PopSift_DIR)
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
Looking for OpenGV.
OpenGV headers not found!
Could NOT find OpenGV (missing: OPENGV_LIBRARY OPENGV_INCLUDE_DIR) 
Found ZLIB: C:/ProgramData/Anaconda2/Library/lib/z.lib (found version "1.2.8") 
CMake Warning at src/cmakeFindModules/FindOpenEXR.cmake:56 (message):
  GENERIC_INCLUDE_PATHS: /include;/include
Call Stack (most recent call first):
  src/cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  src/CMakeLists.txt:451 (find_package)

CMake Warning at src/cmakeFindModules/FindOpenEXR.cmake:57 (message):
  Test if file exist:
  OPENEXR_INCLUDE_PATH-NOTFOUND/OpenEXR/ImfMultiPartInputFile.h
Call Stack (most recent call first):
  src/cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  src/CMakeLists.txt:451 (find_package)

CMake Warning at src/cmakeFindModules/FindOpenEXR.cmake:72 (message):
  No, default to 1.6.1
Call Stack (most recent call first):
  src/cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  src/CMakeLists.txt:451 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenEXR (missing: ILMBASE_INCLUDE_PATH OPENEXR_INCLUDE_PATH
  OPENEXR_IMATH_LIBRARY OPENEXR_ILMIMF_LIBRARY OPENEXR_IEX_LIBRARY
  OPENEXR_HALF_LIBRARY) (found version "1.6.1")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  src/cmakeFindModules/FindOpenEXR.cmake:157 (find_package_handle_standard_args)
  src/cmakeFindModules/FindOpenImageIO.cmake:1 (find_package)
  src/CMakeLists.txt:451 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory E:/AliceVision/AliceVision/src
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/stlplus3
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/stlplus3
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/lemon
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/lemon
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/lemon/lemon
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/lemon/lemon
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/vectorGraphics
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/vectorGraphics
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/cxsparse
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/cxsparse
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/ceres-solver
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/ceres-solver/internal/ceres
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/ceres-solver/internal/ceres
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/flann
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/flann/cmake
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/flann/src
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/flann/src/cpp
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/flann/src/cpp
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Cholesky
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/CholmodSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/products
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/util
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/arch
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/arch/SSE
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/arch/AltiVec
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/arch/NEON
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Core/arch/Default
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Eigen2Support
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Eigen2Support/Geometry
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Eigenvalues
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Geometry
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Geometry/arch
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Householder
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/IterativeLinearSolvers
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/Jacobi
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/LU
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/LU/arch
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/MetisSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/OrderingMethods
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/PaStiXSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/PardisoSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/QR
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SPQRSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SVD
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SparseCholesky
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SparseCore
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SparseLU
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SparseQR
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/StlSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/SuperLUSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/UmfPackSupport
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/misc
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/Eigen/src/plugins
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/AutoDiff
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/BVH
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/FFT
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/IterativeSolvers
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/MatrixFunctions
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/MoreVectorization
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/NonLinearOptimization
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/NumericalDiff
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/Polynomials
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/Skyline
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/SparseExtra
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/KroneckerProduct
   used as include directory in directory E:/AliceVision/AliceVision/src/dependencies/eigen/unsupported/Eigen/src/Splines

Configuring incomplete, errors occurred!
See also "E:/AliceVision/AliceVision/Build_/CMakeFiles/CMakeOutput.log".
See also "E:/AliceVision/AliceVision/Build_/CMakeFiles/CMakeError.log".

**Comment by simogasp** [comment] 2018-02-10 12:05
> CMake Error at src/CMakeLists.txt:316 (message):
Failed to find Boost.

It does not find Boost which is a required dependency. If you don't have it installed in your system, you need to download and install it http://www.boost.org/users/download/ (note there are windows binary if you want to spare the pain of compiling).
If you install it in a system directory then you should be able to run cmake again. If you installed it in a custom folder then you need to pass `-DBOOST_ROOT:PATH=path/to/boost/install` when you do cmake. (https://cmake.org/cmake/help/v3.0/module/FindBoost.html)

That being said, I must warn you that AFAIK you may be the first one to try the windows compilation: a lot of things has changed and the windows version has never been tested. It would be great if you can contribute to this (obviously we will assist you in the process).

**Comment by yann-lty** [comment] 2018-02-11 11:58
Hi !
I would recommend using [vcpkg ](https://github.com/Microsoft/vcpkg) to get required dependencies (boost, openimageio) as it greatly simplifies build process for those libraries and provide a centralized environment to manage and use them.
FYI, Windows build is also being discussed here: https://github.com/alicevision/AliceVision/issues/345

**Comment by simogasp** [comment] 2018-02-12 08:50
As proposed by @yann-lty you are better off using [vcpkg](https://github.com/Microsoft/vcpkg) as you are going to have the same problem with the other external dependencies.

**Comment by gnatty7** [comment] 2018-05-22 00:59
I got decently far trying to build with VCPKG.  I had to modify the `CMakeLists.txt` for `OpenImageIO` to add `/bigobj` to a couple of other source files:

Added two more entries after the `imagebufalgo_pixelmath.cpp` to
`buildtrees\openimageio\src\oiio-Release-1.8.9\src\libOpenImageIO\CMakeLists.txt`
See below:
```
if (MSVC)
    set_property (SOURCE imagebufalgo_pixelmath.cpp APPEND_STRING PROPERTY COMPILE_FLAGS " /bigobj ")
    set_property (SOURCE imagebufalgo_copy.cpp APPEND_STRING PROPERTY COMPILE_FLAGS " /bigobj ")
    set_property (SOURCE imagebuf.cpp APPEND_STRING PROPERTY COMPILE_FLAGS " /bigobj ")
endif ()
```

However, when I try to configure using the included command:
```
# Windows: Visual 2015
cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 14 2015" -A x64 -T v140,host=x64
```

It errors with the following CMakeError.log:
```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: D:/Work/Code/aliceVision/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_94a0d.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 5/21/2018 5:51:36 PM.

The target "CopyLocalFilesOutputGroup" listed in a BeforeTargets attribute at "D:\Work\Code\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets (80,82)" does not exist in the project, and will be ignored.

Project "D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\cmTC_94a0d.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_94a0d.dir\Debug\".

  Creating directory "D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_94a0d.dir\Debug\cmTC_94a0d.tlog\".

InitializeBuildStatus:

  Creating "cmTC_94a0d.dir\Debug\cmTC_94a0d.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

VcpkgTripletSelection:

  Not using Vcpkg because VcpkgEnabled is "false"

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /arch:AVX2 /Zc:wchar_t /Zc:forScope /Zc:inline /openmp /Fo"cmTC_94a0d.dir\Debug\\" /Fd"cmTC_94a0d.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /arch:AVX2 /Zc:wchar_t /Zc:forScope /Zc:inline /openmp /Fo"cmTC_94a0d.dir\Debug\\" /Fd"cmTC_94a0d.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  

  CheckIncludeFile.c

D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\cmTC_94a0d.vcxproj]

Done Building Project "D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\cmTC_94a0d.vcxproj" (default targets) -- FAILED.



Build FAILED.



"D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\cmTC_94a0d.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\Work\Code\aliceVision\build\CMakeFiles\CMakeTmp\cmTC_94a0d.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.52
```

Really not sure why it's trying to use `pthread.h` on Windows.

**Comment by gnatty7** [comment] 2018-05-22 02:14
So, I made some more progress.  Somehow, I needed to install CUDA, for this error to go away, so I installed the latest version from Nvidia (9.2) and changed the command line to read:
```
cmake .. -DCUDA_TOOLKIT_ROOT_DIR="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 14 2015" -A x64 -T v140,host=x64
```
So that it could pick up the CUDA root.

This allowed me to get a `.sln` file generated.  However, these libraries are still not found:
```
-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Ghostscript (missing: GHOSTSCRIPT_EXECUTABLE)
-- Could NOT find GLPK (missing: GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing: ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)
-- Could NOT find COIN (missing: COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY)
-- Could NOT find SOPLEX (missing: SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)
```

I opened the `.sln` file and most of the library built, however, several targets did not and these are those that used the `AlembicImporter` and `AlembicExporter`.
The problem was that `half.h` is not being located, and when I looked at the failing projects
`aliceVision_sfm`
and
`aliceVision_keyframe`
I noticed that for some reason, the OpenEXR area of the vcpkg area wasn't included in the *Include Paths*

I added this directory, and got those target to build.

Not sure why because `OpenEXR` is automatically installed as a dependency along with `OpenImageIO` when it is installed but it doesn't set-up the include directory properly.

Perhaps this is an oversight in the `CMakeLists.txt` for those targets.

**Comment by fabiencastan** [comment] 2018-06-15 20:18
The problem is that Alembic doesn't propagate ilmbase include path correctly. A workaround has been merged into the develop branch.

Do you still have troubles or should we close the issue?

**Comment by natowi** [comment] 2019-02-02 16:35
I am trying to build the latest alicevision release, any tips?
With Vcpkg I get stuck at:
CMake Error at src/CMakeLists.txt:148 (message):
submodule(s) are missing, please update your repository:
    > git submodule update -i
--
and with cmake-gui:
I get the message "Error in configuration process, project files may be invalid".
I have to select "ALICEVISION_BUILD_DEPENDENCIES" and I can open the project in VS2017.
Changed target to release and started building. Build process hangs up at some point.

**Closed** 2020-03-09 17:47 UTC
Labels: scope:build, windows
