### ISSUE TITLE
home brew  error

### ISSUE THREAD

**Issue by tub-sgg** [alicevision/AliceVision#717] opened 2019-11-30 14:43 UTC
Last 15 lines from /Users/Alex/Library/Logs/Homebrew/alicevision/02.make:
cd /tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/src/aliceVision/matchingImageCollection && /usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_link_script CMakeFiles/aliceVision_matchingImageCollection.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/include/darwin -march=ivybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -O3 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 2.0.0 -current_version 2.2.0 -o ../../../Darwin-x86_64/libaliceVision_matchingImageCollection.2.2.dylib -install_name @rpath/libaliceVision_matchingImageCollection.2.dylib CMakeFiles/aliceVision_matchingImageCollection.dir/matchingCommon.cpp.o CMakeFiles/aliceVision_matchingImageCollection.dir/ImageCollectionMatcher_generic.cpp.o CMakeFiles/aliceVision_matchingImageCollection.dir/ImageCollectionMatcher_cascadeHashing.cpp.o CMakeFiles/aliceVision_matchingImageCollection.dir/GeometricFilterMatrix_HGrowing.cpp.o CMakeFiles/aliceVision_matchingImageCollection.dir/geometricFilterUtils.cpp.o CMakeFiles/aliceVision_matchingImageCollection.dir/pairBuilder.cpp.o -Wl,-rpath,/tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/Darwin-x86_64 ../../../Darwin-x86_64/libaliceVision_sfmData.2.2.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libboost_container-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_graph-mt.dylib /usr/local/lib/libboost_log-mt.dylib /usr/local/lib/libboost_log_setup-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_serialization-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_timer-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libspqr.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib /usr/local/lib/libcholmod.dylib /usr/local/lib/libccolamd.dylib /usr/local/lib/libcamd.dylib /usr/local/lib/libcolamd.dylib /usr/local/lib/libamd.dylib /usr/local/opt/openblas/lib/libopenblas.dylib /usr/local/opt/openblas/lib/libopenblas.dylib /usr/local/lib/libsuitesparseconfig.dylib /usr/local/lib/libmetis.dylib ../../../Darwin-x86_64/libaliceVision_multiview.2.2.dylib /usr/local/lib/libceres.1.14.0.dylib /usr/local/lib/libglog.dylib /usr/local/lib/libgflags.2.2.2.dylib ../../../Darwin-x86_64/libaliceVision_matching.2.2.dylib ../../../Darwin-x86_64/libaliceVision_feature.2.2.dylib ../../../Darwin-x86_64/libaliceVision_gpu.2.2.dylib ../../../Darwin-x86_64/libvlsift.a ../../../Darwin-x86_64/libaliceVision_image.2.2.dylib /usr/local/lib/libOpenImageIO.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIlmThread.dylib -ldl ../../../Darwin-x86_64/libaliceVision_geometry.2.2.dylib ../../../Darwin-x86_64/libaliceVision_system.2.2.dylib ../../../Darwin-x86_64/libaliceVision_numeric.2.2.dylib ../../../Darwin-x86_64/liblib_clp.a ../../../Darwin-x86_64/liblib_OsiClpSolver.a ../../../Darwin-x86_64/liblib_CoinUtils.a ../../../Darwin-x86_64/liblib_Osi.a /usr/local/lib/libboost_container-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_log-mt.dylib /usr/local/lib/libboost_log_setup-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libspqr.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib /usr/local/lib/libcholmod.dylib /usr/local/lib/libccolamd.dylib /usr/local/lib/libcamd.dylib /usr/local/lib/libcolamd.dylib /usr/local/lib/libamd.dylib /usr/local/opt/openblas/lib/libopenblas.dylib /usr/local/lib/libsuitesparseconfig.dylib /usr/local/lib/libmetis.dylib 
cd /tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/src/aliceVision/matchingImageCollection && /usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_symlink_library ../../../Darwin-x86_64/libaliceVision_matchingImageCollection.2.2.dylib ../../../Darwin-x86_64/libaliceVision_matchingImageCollection.2.dylib ../../../Darwin-x86_64/libaliceVision_matchingImageCollection.dylib
[ 71%] Built target aliceVision_matchingImageCollection
[ 71%] Linking CXX shared library ../../../Darwin-x86_64/libaliceVision_mesh.dylib
cd /tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/src/aliceVision/mesh && /usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_link_script CMakeFiles/aliceVision_mesh.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/include/darwin -march=ivybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -O3 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 2.0.0 -current_version 2.2.0 -o ../../../Darwin-x86_64/libaliceVision_mesh.2.2.dylib -install_name @rpath/libaliceVision_mesh.2.dylib CMakeFiles/aliceVision_mesh.dir/Mesh.cpp.o CMakeFiles/aliceVision_mesh.dir/MeshAnalyze.cpp.o CMakeFiles/aliceVision_mesh.dir/MeshClean.cpp.o CMakeFiles/aliceVision_mesh.dir/MeshEnergyOpt.cpp.o CMakeFiles/aliceVision_mesh.dir/meshPostProcessing.cpp.o CMakeFiles/aliceVision_mesh.dir/meshVisibility.cpp.o CMakeFiles/aliceVision_mesh.dir/Texturing.cpp.o CMakeFiles/aliceVision_mesh.dir/UVAtlas.cpp.o -Wl,-rpath,/tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/Darwin-x86_64 ../../../Darwin-x86_64/libaliceVision_mvsUtils.2.2.dylib /usr/local/lib/libgeogram.dylib /usr/local/lib/libboost_filesystem-mt.dylib ../../../Darwin-x86_64/libaliceVision_mvsData.2.2.dylib /usr/local/opt/zlib/lib/libz.dylib ../../../Darwin-x86_64/libaliceVision_sfmData.2.2.dylib /usr/local/lib/libboost_filesystem-mt.dylib ../../../Darwin-x86_64/libaliceVision_multiview.2.2.dylib /usr/local/lib/libceres.1.14.0.dylib /usr/local/lib/libglog.dylib /usr/local/lib/libgflags.2.2.2.dylib /usr/local/lib/libspqr.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib /usr/local/lib/libcholmod.dylib /usr/local/lib/libccolamd.dylib /usr/local/lib/libcamd.dylib /usr/local/lib/libcolamd.dylib /usr/local/lib/libamd.dylib /usr/local/opt/openblas/lib/libopenblas.dylib /usr/local/lib/libsuitesparseconfig.dylib /usr/local/lib/libmetis.dylib ../../../Darwin-x86_64/libaliceVision_matching.2.2.dylib ../../../Darwin-x86_64/libaliceVision_feature.2.2.dylib ../../../Darwin-x86_64/libaliceVision_gpu.2.2.dylib ../../../Darwin-x86_64/libvlsift.a ../../../Darwin-x86_64/libaliceVision_image.2.2.dylib /usr/local/lib/libOpenImageIO.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIlmThread.dylib -ldl ../../../Darwin-x86_64/libaliceVision_geometry.2.2.dylib ../../../Darwin-x86_64/libaliceVision_system.2.2.dylib /usr/local/lib/libboost_log-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_log_setup-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib ../../../Darwin-x86_64/libaliceVision_numeric.2.2.dylib ../../../Darwin-x86_64/liblib_clp.a ../../../Darwin-x86_64/liblib_OsiClpSolver.a ../../../Darwin-x86_64/liblib_CoinUtils.a ../../../Darwin-x86_64/liblib_Osi.a /usr/local/lib/libboost_container-mt.dylib 
cd /tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/src/aliceVision/mesh && /usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_symlink_library ../../../Darwin-x86_64/libaliceVision_mesh.2.2.dylib ../../../Darwin-x86_64/libaliceVision_mesh.2.dylib ../../../Darwin-x86_64/libaliceVision_mesh.dylib
[ 71%] Built target aliceVision_mesh
[ 71%] Linking CXX executable ../../../Darwin-x86_64/aliceVision_meshDenoising
cd /tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/src/software/pipeline && /usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_link_script CMakeFiles/aliceVision_meshDenoising.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -I/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/include/darwin -march=ivybridge -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mno-sse4a -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -O3 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/aliceVision_meshDenoising.dir/main_meshDenoising.cpp.o  -o ../../../Darwin-x86_64/aliceVision_meshDenoising-1.0 -Wl,-rpath,/tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/Darwin-x86_64 ../../../Darwin-x86_64/libaliceVision_mvsUtils.2.2.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libboost_container-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_graph-mt.dylib /usr/local/lib/libboost_log-mt.dylib /usr/local/lib/libboost_log_setup-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_serialization-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_timer-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib ../../../Darwin-x86_64/libaliceVision_mvsData.2.2.dylib /usr/local/opt/zlib/lib/libz.dylib ../../../Darwin-x86_64/libaliceVision_sfmData.2.2.dylib ../../../Darwin-x86_64/libaliceVision_multiview.2.2.dylib /usr/local/lib/libceres.1.14.0.dylib /usr/local/lib/libglog.dylib /usr/local/lib/libgflags.2.2.2.dylib /usr/local/lib/libspqr.dylib /usr/local/lib/libtbb.dylib /usr/local/lib/libtbbmalloc.dylib /usr/local/lib/libcholmod.dylib /usr/local/lib/libccolamd.dylib /usr/local/lib/libcamd.dylib /usr/local/lib/libcolamd.dylib /usr/local/lib/libamd.dylib /usr/local/opt/openblas/lib/libopenblas.dylib /usr/local/lib/libsuitesparseconfig.dylib /usr/local/lib/libmetis.dylib ../../../Darwin-x86_64/libaliceVision_matching.2.2.dylib ../../../Darwin-x86_64/libaliceVision_feature.2.2.dylib ../../../Darwin-x86_64/libaliceVision_gpu.2.2.dylib ../../../Darwin-x86_64/libvlsift.a ../../../Darwin-x86_64/libaliceVision_image.2.2.dylib /usr/local/lib/libOpenImageIO.dylib /usr/local/lib/libImath.dylib /usr/local/lib/libIex.dylib /usr/local/lib/libHalf.dylib /usr/local/lib/libIlmThread.dylib -ldl ../../../Darwin-x86_64/libaliceVision_geometry.2.2.dylib ../../../Darwin-x86_64/libaliceVision_system.2.2.dylib ../../../Darwin-x86_64/libaliceVision_numeric.2.2.dylib ../../../Darwin-x86_64/liblib_clp.a ../../../Darwin-x86_64/liblib_OsiClpSolver.a ../../../Darwin-x86_64/liblib_CoinUtils.a ../../../Darwin-x86_64/liblib_Osi.a ../../../Darwin-x86_64/libOpenMesh.a /usr/local/lib/libboost_container-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_log-mt.dylib /usr/local/lib/libboost_log_setup-mt.dylib /usr/local/lib/libboost_program_options-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib 
cd /tmp/alicevision-20191130-3167-7l9dgs/AliceVision-2.2.0/build/src/software/pipeline && /usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_symlink_executable ../../../Darwin-x86_64/aliceVision_meshDenoising-1.0 ../../../Darwin-x86_64/aliceVision_meshDenoising
[ 71%] Built target aliceVision_meshDenoising
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/ryanfb/homebrew-alicevision/issues

### Problem

**Expected behavior:**  

**Actual behavior:**  

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

* AliceVision branch/version:
* OS: 
* C++ compiler:

**Comment by natowi** [comment] 2019-11-30 19:22
Duplicate of https://github.com/ryanfb/homebrew-alicevision/issues/8

**Closed by natowi** 2019-11-30 19:22 UTC
